VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "juku-oracle"
  config.vm.network "forwarded_port", guest: 1521, host: 1521
  config.vm.boot_timeout = 120
  config.vm.provider "virtualbox" do |vb|
        vb.cpus = 2
        vb.memory = 2048
    vb.gui = false
  end
end
