VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "juku-oracle"
  config.vm.network "forwarded_port", guest: 1521, host: 1521
  config.vm.network "forwarded_port", guest: 80, host: 50000
  config.vm.boot_timeout = 240
  config.vm.define "juku-oracle" do |juku_oracle|
  end
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 2048
    vb.gui = false
    vb.name = "juku-oracle"
  end
end
